---
  extends:
    - eslint-config-airbnb-es5
  globals:
    define: true
    ga: true
    SVGAnim: true
    Stickyfill: true
  rules:
    one-var: 0
    comma-dangle: 0
    guard-for-in: 0
    new-parens: 0
    new-cap: 0
    func-names: 0
    valid-jsdoc: 0
    no-multi-str: 0
    no-loop-func: 1
    camelcase: 0
    spaced-comment: 0
    space-before-function-paren: 0
    indent: [2, 2, {"SwitchCase": 1}]

