---
  extends:
    - eslint-config-airbnb-es5
  globals:
    define: true
    ga: true
    $: true
  rules:
    one-var: 0
    comma-dangle: 0
    guard-for-in: 0
    new-parens: 0
    new-cap: 0
    func-names: 0
    valid-jsdoc: 0
    no-multi-str: 0
    no-loop-func: 1
    guard-for-in: 1
    space-before-function-paren: 0
    indent: [2, 2, {"SwitchCase": 1}]

