#! /bin/bash
redis-cli flushall
echo ''
echo '*********************************************************'
echo '*                                                       *'
echo '* Cache clean!                                          *'
echo '*                                                       *'
echo '*********************************************************'

foreman start
