ADMIN_BOUNDARY_ID = "admin"
CDB_INDICATORS_VALUES_TABLE = "gfw_climate_country_pages_indicator_values_2017_data"
CDB_INDICATORS_TABLE = "gfw_climate_country_pages_indicator_info_2017_data"
CDB_BOUNDARIES_TABLE="gfw_climate_country_pages_boundary_info_2017_data"
CDB_COUNTRIES_TABLE = "gadm28_countries"
CDB_SUBNAT_TABLE = "gadm28_adm1"
